plugins {
    id 'plugin-commons'
}

base.archivesName = 'pistongradle'

dependencies {
    implementation projects.settingsPlugin

    implementation(libs.bundles.mcd) {
        exclude module: 'jpot-simple'
    }
    implementation variantOf(libs.diffpatch) { classifier('all') }
}

gradlePlugin {
    // Define the plugin
    plugins {
        pistonGradle {
            id = 'org.pistonmc.build'
            implementationClass = 'org.pistonmc.build.gradle.PistonGradlePlugin'
        }
    }
}